/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SignUp_Design;


import Dashboard_Design.DashboardMain_Design;
import Dashboard_Design.Report_Design;
import Main.DBConnection;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.security.Security;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author Darkheart
 */
public class SignUpStep02 extends javax.swing.JFrame {

    /**
     * Creates new form SignUpStep02
     */
    
    public Connection Conn = null;
    public Statement stmt = null;
    public String sql="";
    public ResultSet rs = null;
    public String s = null;
    public String path = null;
    public SignUpStep01 Back = null;
    private static String EmailUname;
    private static String EmailPass;
    
    
    public SignUpStep02(SignUpStep01 form) {
        initComponents();
        Back = form;
        Conn = DBConnection.getconn();
        DPPanel.setBackground(new Color(242,242,242));
        DPPanel.setVisible(false);
        ResendBTN.setVisible(false);
        VerifyBTN.setVisible(false);
        SignUpBTN.setVisible(false);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelBTN = new javax.swing.JButton();
        DPPanel = new javax.swing.JPanel();
        DP = new javax.swing.JLabel();
        BrowseIMG = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        EmailAndVCodeLBL = new javax.swing.JLabel();
        EVTextBox = new javax.swing.JTextField();
        EmailAndVcodeTextboxLBL = new javax.swing.JLabel();
        SubmitBTN = new javax.swing.JButton();
        VerifyBTN = new javax.swing.JButton();
        SignUpBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        ResendBTN = new javax.swing.JButton();
        BackgroundUI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CancelBTN.setBackground(new java.awt.Color(242, 242, 242));
        CancelBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTN.png"))); // NOI18N
        CancelBTN.setBorder(null);
        CancelBTN.setContentAreaFilled(false);
        CancelBTN.setIconTextGap(0);
        CancelBTN.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CancelBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNPressed.png"))); // NOI18N
        CancelBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNRollOver.png"))); // NOI18N
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 3, -1, -1));

        DPPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        DPPanel.setForeground(new java.awt.Color(242, 242, 242));
        DPPanel.setFocusable(false);
        DPPanel.setRequestFocusEnabled(false);
        DPPanel.setVerifyInputWhenFocusTarget(false);
        DPPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DPPanel.add(DP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, 50));

        BrowseIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/BrowseBTNNormal.png"))); // NOI18N
        BrowseIMG.setContentAreaFilled(false);
        BrowseIMG.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/BrowseBTNSelect.png"))); // NOI18N
        BrowseIMG.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/BrowseBTNRoll.png"))); // NOI18N
        BrowseIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseIMGActionPerformed(evt);
            }
        });
        DPPanel.add(BrowseIMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 120, -1));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Upload Profile Picture");
        DPPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, -1));

        getContentPane().add(DPPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 440, 290));

        EmailAndVCodeLBL.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        EmailAndVCodeLBL.setForeground(java.awt.SystemColor.windowBorder);
        EmailAndVCodeLBL.setText("Email Address");
        getContentPane().add(EmailAndVCodeLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 140, 20));

        EVTextBox.setBorder(null);
        EVTextBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EVTextBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EVTextBoxFocusLost(evt);
            }
        });
        getContentPane().add(EVTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 266, 360, 20));

        EmailAndVcodeTextboxLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/EmailAndVcodeTextBox.png"))); // NOI18N
        getContentPane().add(EmailAndVcodeTextboxLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 410, 50));

        SubmitBTN.setBackground(new java.awt.Color(242, 242, 242));
        SubmitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SubmitBTNNormal.png"))); // NOI18N
        SubmitBTN.setBorder(null);
        SubmitBTN.setContentAreaFilled(false);
        SubmitBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SumbitBTNSelect.png"))); // NOI18N
        SubmitBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SumbitBTNRoll.png"))); // NOI18N
        SubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 120, 50));

        VerifyBTN.setBackground(new java.awt.Color(242, 242, 242));
        VerifyBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/VerifyNormalBTN.png"))); // NOI18N
        VerifyBTN.setBorder(null);
        VerifyBTN.setContentAreaFilled(false);
        VerifyBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/VerifyBTNSelect.png"))); // NOI18N
        VerifyBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/VerifyBTNRoll.png"))); // NOI18N
        VerifyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyBTNActionPerformed(evt);
            }
        });
        getContentPane().add(VerifyBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 120, 50));

        SignUpBTN.setBackground(new java.awt.Color(242, 242, 242));
        SignUpBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpNormalBTN.png"))); // NOI18N
        SignUpBTN.setBorder(null);
        SignUpBTN.setContentAreaFilled(false);
        SignUpBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpBTNSelected.png"))); // NOI18N
        SignUpBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpRoll.png"))); // NOI18N
        SignUpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 120, 50));

        BackBTN.setBackground(new java.awt.Color(242, 242, 242));
        BackBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/BackNormalBTN.png"))); // NOI18N
        BackBTN.setBorder(null);
        BackBTN.setContentAreaFilled(false);
        BackBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/BackSelect.png"))); // NOI18N
        BackBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/BackRoll.png"))); // NOI18N
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });
        getContentPane().add(BackBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 120, 50));

        ResendBTN.setBackground(new java.awt.Color(242, 242, 242));
        ResendBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/ResendNormalBTN.png"))); // NOI18N
        ResendBTN.setBorder(null);
        ResendBTN.setContentAreaFilled(false);
        ResendBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/ResendSelected.png"))); // NOI18N
        ResendBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/ResendBTNRoll.png"))); // NOI18N
        ResendBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResendBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ResendBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 120, 50));

        BackgroundUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp Step 02.png"))); // NOI18N
        BackgroundUI.setDoubleBuffered(true);
        getContentPane().add(BackgroundUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void EVTextBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EVTextBoxFocusGained
        EmailAndVcodeTextboxLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/EmailAndVcodeTextBoxFocus.png"));
    }//GEN-LAST:event_EVTextBoxFocusGained

    private void EVTextBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EVTextBoxFocusLost
        EmailAndVcodeTextboxLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/EmailAndVcodeTextBox.png"));
    }//GEN-LAST:event_EVTextBoxFocusLost
    private int randomCode;
    private String Email;
    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed

       if(validateEmailAddress(EVTextBox.getText()))
       {
        EmailAndVCodeLBL.setText("Verification Code");
        Email = EVTextBox.getText();
        EVTextBox.setText("");
        SubmitBTN.setVisible(false);
        
        BackBTN.setVisible(false);
        ResendBTN.setVisible(true);
        VerifyBTN.setVisible(true);
        
           
        System.out.println("Submit BTN pressed!");
        SendMail("Verification code has been send to the Email");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Enter Valid Email Address..");
        }

    }//GEN-LAST:event_SubmitBTNActionPerformed
    
    private void ReadConfig()
    {
        BufferedReader br = null;
        try {
            File file = new File("Config.txt"); // java.io.File
            FileReader fr = new FileReader(file); // java.io.FileReader
            br = new BufferedReader(fr); // java.io.BufferedReader
            String line;
            while ((line = br.readLine()) != null) 
            {
              // process the line

		if (line.startsWith("MailUN")) 
                { // check for a value (string starting with "")
                    
                    EmailUname = line.substring(6).trim(); // show it in the label in the userinterface
                    System.out.println("Username- "+EmailUname);
		}
              
                if (line.startsWith("MailPW")) 
                { // check for a value (string starting with "")
                    
                    EmailPass = line.substring(6).trim(); // show it in the label in the userinterface
                    System.out.println("Password- "+EmailPass);
		}
            }
          }
          catch(IOException e) { e.printStackTrace();}
          finally
          {
              try { if (br != null) {
                  br.close();
              } }
              catch(IOException e) { e.printStackTrace(); }
          }
        
    }
    
    private void SendMail(String showmsg)
    {
        
        //covidcareverify@gmail.com
        //Covidcare2021
        
        ReadConfig();
        
        try{
        Random rand = new Random();
        randomCode=rand.nextInt(999999);
        String host = "smtp.gmail.com";
        String user = EmailUname;
        String pass = EmailPass;
        String to = Email;
        String subject="Verification code";
        String message ="Your Verification code is "+randomCode;
        boolean sessionDebug = false;
        Properties pros = System.getProperties();
        pros.put("mail.smtp.starttls.enable", "true");
        pros.put("mail.smtp.host", "host");
        pros.put("mail.smtp.port","587");
        pros.put("mail.smtp.auth","true");
        pros.put("mail.smtp.starttls.required", "true");
        java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
        Session mailSession = Session.getDefaultInstance(pros, null);
        mailSession.setDebug(sessionDebug);
        Message msg = new MimeMessage(mailSession);
        msg.setFrom(new InternetAddress(user));
        InternetAddress [] address = {new InternetAddress(to)};
        msg.setRecipients(Message.RecipientType.TO, address);
        msg.setSubject(subject);
        msg.setText(message);
            try (Transport transport = mailSession.getTransport("smtp")) {
                transport.connect(host, user, pass);
                transport.sendMessage(msg, msg.getAllRecipients());
            }
        JOptionPane.showMessageDialog(null, showmsg);
        }catch(HeadlessException | MessagingException ex){
        JOptionPane.showMessageDialog(rootPane, ex);
        }
                System.out.println("Mail Sent!");
    }
    
    private void VerifyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyBTNActionPerformed
        System.out.println("Verify BTN pressed!");
        if(Integer.valueOf(EVTextBox.getText())==randomCode){
            System.out.println("Code is Correct!");
                    JOptionPane.showMessageDialog(null, "Email Verification Success..");
                    DPPanel.setVisible(true);
                    SignUpBTN.setVisible(true);                    
                    SubmitBTN.setVisible(false);
                    BackBTN.setVisible(false);
                    ResendBTN.setVisible(false);
                    VerifyBTN.setVisible(false);
            }
            else{
            JOptionPane.showMessageDialog(null, "Verification Code is Wrong!");
            }
    }//GEN-LAST:event_VerifyBTNActionPerformed

    public ImageIcon ResizeImage(String imgPath)
        {
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(DP.getWidth(), DP.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }
    
    private void SignUpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBTNActionPerformed
        
        if(s == null)
        {
            JOptionPane.showMessageDialog(null, "Upload a profile picture!");
        }
        else{
            try {
  
            sql = "insert into Users values(?,?,?,?,?,?,?,?)";
            PreparedStatement ps = (PreparedStatement) Conn.prepareStatement(sql);
            InputStream is = new FileInputStream(new File(s));
            String Role = "user";
            ps.setString(1, Back.Username.getText());
            ps.setString(2, Back.Fname.getText());
            ps.setString(3, Back.Lname.getText());
            ps.setString(4, Back.ID.getText());
            ps.setString(5, String.valueOf(Back.Password.getPassword()));
            ps.setString(6, Email);
            ps.setBlob(7,is);
            ps.setString(8, Role);
            
            ps.executeUpdate();
            
            //stmt = Conn.createStatement();
            //sql = "insert into Users values('"+back.Signup_Username.getText()+"','"+back.FirstName.getText()+"','"+back.LastName.getText()+"',"+back.DoctorID.getText()+",'"+String.valueOf(back.SignUp_Password.getPassword())+"','"+SecurityQ.getSelectedItem().toString()+"','"+SQAnswer.getText()+"','"+is+"')";
            //stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Sign up successful!");
            
                    
                    DashboardMain_Design Dash = new DashboardMain_Design();
                    Dash.UpdataDP(Back.Username.getText());
                    Dash.DashUserNameLBL.setText(Back.Username.getText());
                    
                        Dash.Register.TabbedPane.removeTabAt(2);
                        Dash.Register.TabbedPane.removeTabAt(1);
                        
                        Dash.Settings.TabbedPane.removeTabAt(1);
                        Report_Design.roleView = false;
                    
                    this.setVisible(false);
                    this.dispose();
                    Dash.setVisible(true);
        }
            
        catch(HeadlessException | SQLException obj)
        {
            JOptionPane.showMessageDialog(null, obj.toString());
        }   catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(SignUpStep02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        
        }
        
    }//GEN-LAST:event_SignUpBTNActionPerformed

    private void ResendBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResendBTNActionPerformed
        SendMail("Verification code Resent!");
    }//GEN-LAST:event_ResendBTNActionPerformed

    private void BrowseIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowseIMGActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            DP.setIcon(ResizeImage(path));
            s = path;
        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("No Data");
        }
    }//GEN-LAST:event_BrowseIMGActionPerformed

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        this.setVisible(false);
        Back.setVisible(true);
    }//GEN-LAST:event_BackBTNActionPerformed

    
    public Boolean validateEmailAddress(String emailAddress) {

        Pattern regexPattern = Pattern.compile("^[(a-zA-Z-0-9-\\_\\+\\.)]+@[(a-z-A-z)]+\\.[(a-zA-z)]{2,3}$");
        Matcher regMatcher = regexPattern.matcher(emailAddress);
        if(regMatcher.matches()) 
        {
            return true;
        }
        else 
        {
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        
                    try 
                    {
                        UIManager.setLookAndFeel( new FlatLightFlatIJTheme() );
                    } 
                    catch( UnsupportedLookAndFeelException ex ) 
                    {
                        System.err.println( "Failed to initialize LaF" );
                    }
            SignUpStep01 open = new SignUpStep01();
            SignUpStep02 frame = new SignUpStep02(open);
            
            frame.setVisible(true);


                    
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                


                
                //SignUpStep02 frame = new SignUpStep02();
                
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBTN;
    private javax.swing.JLabel BackgroundUI;
    private javax.swing.JButton BrowseIMG;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JLabel DP;
    private javax.swing.JPanel DPPanel;
    private javax.swing.JTextField EVTextBox;
    private javax.swing.JLabel EmailAndVCodeLBL;
    private javax.swing.JLabel EmailAndVcodeTextboxLBL;
    private javax.swing.JButton ResendBTN;
    private javax.swing.JButton SignUpBTN;
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JButton VerifyBTN;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables



}
