/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SignUp_Design;

import Main.DBConnection;
import com.mysql.jdbc.PreparedStatement;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.synth.SynthLookAndFeel;

/**
 *
 * @author Darkheart
 */
public class SignUpStep01 extends javax.swing.JFrame {

    public Connection Conn = null;
    /**
     * Creates new form SignUpStep01
     */
    public SignUpStep01() {
        initComponents();
        Conn = DBConnection.getconn();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelBTN = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        ConfirmPassword = new javax.swing.JPasswordField();
        Username = new javax.swing.JTextField();
        Fname = new javax.swing.JTextField();
        Lname = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        UnameLBL = new javax.swing.JLabel();
        FnameLBL = new javax.swing.JLabel();
        LnameLBL = new javax.swing.JLabel();
        IdLBL = new javax.swing.JLabel();
        PassLBL = new javax.swing.JLabel();
        CpassLBL = new javax.swing.JLabel();
        NextBTN = new javax.swing.JButton();
        BackgroundUI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CancelBTN.setBackground(new java.awt.Color(242, 242, 242));
        CancelBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTN.png"))); // NOI18N
        CancelBTN.setBorder(null);
        CancelBTN.setIconTextGap(0);
        CancelBTN.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CancelBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNPressed.png"))); // NOI18N
        CancelBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNRollOver.png"))); // NOI18N
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 3, -1, -1));

        Password.setBorder(null);
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 300, 20));

        ConfirmPassword.setBorder(null);
        ConfirmPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ConfirmPasswordFocusLost(evt);
            }
        });
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 426, 300, 20));

        Username.setBorder(null);
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 116, 290, 20));

        Fname.setBorder(null);
        Fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FnameFocusLost(evt);
            }
        });
        getContentPane().add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 174, 290, 20));

        Lname.setBorder(null);
        Lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LnameFocusLost(evt);
            }
        });
        getContentPane().add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 290, 20));

        ID.setBorder(null);
        ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFocusLost(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 290, 20));

        UnameLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpTextboxNormal.png"))); // NOI18N
        getContentPane().add(UnameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 340, 50));

        FnameLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpTextboxNormal.png"))); // NOI18N
        getContentPane().add(FnameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 340, 50));

        LnameLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpTextboxNormal.png"))); // NOI18N
        getContentPane().add(LnameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 340, 40));

        IdLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpTextboxNormal.png"))); // NOI18N
        getContentPane().add(IdLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 340, 40));

        PassLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpTextboxNormal.png"))); // NOI18N
        getContentPane().add(PassLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 340, 40));

        CpassLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpTextboxNormal.png"))); // NOI18N
        getContentPane().add(CpassLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 340, 50));

        NextBTN.setBackground(new java.awt.Color(242, 242, 242));
        NextBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/Sign up BTN.png"))); // NOI18N
        NextBTN.setBorder(null);
        NextBTN.setContentAreaFilled(false);
        NextBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/Sign up BTNSelected.png"))); // NOI18N
        NextBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp/SignUpRollover.png"))); // NOI18N
        NextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBTNActionPerformed(evt);
            }
        });
        getContentPane().add(NextBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 120, 40));

        BackgroundUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/SignUp Step 01.png"))); // NOI18N
        getContentPane().add(BackgroundUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        UnameLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxSelected.png"));
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        UnameLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxNormal.png"));
    }//GEN-LAST:event_UsernameFocusLost

    private void FnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameFocusGained
        FnameLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxSelected.png"));
    }//GEN-LAST:event_FnameFocusGained

    private void FnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FnameFocusLost
        FnameLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxNormal.png"));
    }//GEN-LAST:event_FnameFocusLost

    private void LnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameFocusGained
        LnameLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxSelected.png"));
    }//GEN-LAST:event_LnameFocusGained

    private void LnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LnameFocusLost
        LnameLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxNormal.png"));
    }//GEN-LAST:event_LnameFocusLost

    private void IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusGained
        IdLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxSelected.png"));
    }//GEN-LAST:event_IDFocusGained

    private void IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusLost
        IdLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxNormal.png"));
    }//GEN-LAST:event_IDFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        PassLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxSelected.png"));
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        PassLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxNormal.png"));
    }//GEN-LAST:event_PasswordFocusLost

    private void ConfirmPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFocusGained
        CpassLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxSelected.png"));
    }//GEN-LAST:event_ConfirmPasswordFocusGained

    private void ConfirmPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ConfirmPasswordFocusLost
        CpassLBL.setIcon(new ImageIcon("src/UI_Images/SignUp/SignUpTextboxNormal.png"));
    }//GEN-LAST:event_ConfirmPasswordFocusLost

    public boolean checkUsername(String username)    
    {
        PreparedStatement ps;
        ResultSet rs;
        boolean checkUser = false;
        String query = "SELECT * FROM Users WHERE Uname =?";
        
        try {
            ps = (PreparedStatement) Conn.prepareStatement(query);
            ps.setString(1, username);
            
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                checkUser = true;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
         return checkUser;
    }

    private void NextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBTNActionPerformed
        
        String uname = Username.getText();
        String fname = Fname.getText();
        String lname = Lname.getText();
        String docId = ID.getText();
        String pass = String.valueOf(Password.getPassword());
        String re_pass = String.valueOf(ConfirmPassword.getPassword());
        
        
        if(uname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Type Username");
        }
        else if(fname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Type First name");
        }
        
        else if(lname.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Type last name");
        }
        
        else if(docId.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Type ID");
        }
        
        else if(!docId.matches("[0-9]+"))
        {
            JOptionPane.showMessageDialog(null, "ID should be numberic");
        }
                
        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "type A Password");
        }
        else if(!pass.equals(re_pass))
        {
            JOptionPane.showMessageDialog(null, "Retype The Password Again");
        }
        
        else if(checkUsername(uname))
        {
            JOptionPane.showMessageDialog(null, "This Username Already Exist");
        }
        
        else{
            SignUpStep02 next = new SignUpStep02(this);
            this.setVisible(false);
            next.setVisible(true);
        }
        
        
    }//GEN-LAST:event_NextBTNActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpStep01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpStep01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpStep01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpStep01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    try 
                    {
                        UIManager.setLookAndFeel( new SynthLookAndFeel() );
                    } catch( UnsupportedLookAndFeelException ex ) 
                    {
                        System.err.println( "Failed to initialize LaF" );
                    }
                
                    new SignUpStep01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundUI;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JLabel CpassLBL;
    public javax.swing.JTextField Fname;
    private javax.swing.JLabel FnameLBL;
    public javax.swing.JTextField ID;
    private javax.swing.JLabel IdLBL;
    public javax.swing.JTextField Lname;
    private javax.swing.JLabel LnameLBL;
    private javax.swing.JButton NextBTN;
    private javax.swing.JLabel PassLBL;
    public javax.swing.JPasswordField Password;
    private javax.swing.JLabel UnameLBL;
    public javax.swing.JTextField Username;
    // End of variables declaration//GEN-END:variables
}
