/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_Design;

import Dashboard_Design.DashboardMain_Design;
import Dashboard_Design.Report_Design;
import ForgotPassword_Design.ForgotPassword;
import Main.DBConnection;
import SignUp_Design.SignUpStep01;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Darkheart
 */
public class Login extends javax.swing.JFrame {

    
    public Connection Conn = null;
    public Statement stmt = null;
    public String sql = "";
    public ResultSet rs = null;
    public PreparedStatement pst = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
            Conn = DBConnection.getconn();
        

            passCheckBox.setSelected(true);
            Sh = true;
            if(passCheckBox.isSelected())
                {
                Password.setEchoChar((char)0);
                VisibleBTN.setIcon(new ImageIcon("src/UI_Images/Login/visibility.png"));
                }
            else{

                Password.setEchoChar('●');
                VisibleBTN.setIcon(new ImageIcon("src/UI_Images/Login/visibility-off.png"));
                }
                Username.setText("Username");
                Password.setText("Password");

                Action action = new AbstractAction()
                {
                    @Override
                    public void actionPerformed(ActionEvent e)
                    {
                        
                        LoginBTN.doClick();
                    }
                };

                
                    Password.addActionListener( action );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Username = new javax.swing.JTextField();
        VisibleBTN = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        PasswordTxtBoxIcon = new javax.swing.JLabel();
        passCheckBox = new javax.swing.JCheckBox();
        UsernameTxtBoxIcon = new javax.swing.JLabel();
        LoginBTN = new javax.swing.JButton();
        SignUpBTN = new javax.swing.JButton();
        ForgotPassBTN = new javax.swing.JButton();
        CancelBTN = new javax.swing.JButton();
        BackgroundUI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Username.setBorder(null);
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsernameMouseExited(evt);
            }
        });
        getContentPane().add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 280, 30));

        VisibleBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/visibility-off.png"))); // NOI18N
        VisibleBTN.setBorder(null);
        VisibleBTN.setContentAreaFilled(false);
        VisibleBTN.setFocusPainted(false);
        VisibleBTN.setFocusable(false);
        VisibleBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VisibleBTNMouseClicked(evt);
            }
        });
        VisibleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisibleBTNActionPerformed(evt);
            }
        });
        getContentPane().add(VisibleBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 30, 30));

        Password.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Password.setBorder(null);
        Password.setEchoChar('\u25cf');
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordMouseExited(evt);
            }
        });
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 280, 30));

        PasswordTxtBoxIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/TextBoxNormal.png"))); // NOI18N
        PasswordTxtBoxIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PasswordTxtBoxIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PasswordTxtBoxIconMouseExited(evt);
            }
        });
        getContentPane().add(PasswordTxtBoxIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 330, 50));

        passCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        passCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        passCheckBox.setBorder(null);
        passCheckBox.setContentAreaFilled(false);
        passCheckBox.setFocusPainted(false);
        passCheckBox.setFocusable(false);
        getContentPane().add(passCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, -1, -1));

        UsernameTxtBoxIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/TextBoxNormal.png"))); // NOI18N
        UsernameTxtBoxIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsernameTxtBoxIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsernameTxtBoxIconMouseExited(evt);
            }
        });
        getContentPane().add(UsernameTxtBoxIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 330, 50));

        LoginBTN.setBackground(new java.awt.Color(242, 242, 242));
        LoginBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/LoginBTN.png"))); // NOI18N
        LoginBTN.setBorder(null);
        LoginBTN.setBorderPainted(false);
        LoginBTN.setContentAreaFilled(false);
        LoginBTN.setFocusPainted(false);
        LoginBTN.setIconTextGap(0);
        LoginBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/LoginClick.png"))); // NOI18N
        LoginBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/Login.png"))); // NOI18N
        LoginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTNActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 120, 40));

        SignUpBTN.setBackground(new java.awt.Color(242, 242, 242));
        SignUpBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/Sign up text.png"))); // NOI18N
        SignUpBTN.setBorder(null);
        SignUpBTN.setContentAreaFilled(false);
        SignUpBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/Sign up text Clicked.png"))); // NOI18N
        SignUpBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/Don't have an Account.png"))); // NOI18N
        SignUpBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SignUpBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 190, 20));

        ForgotPassBTN.setBackground(new java.awt.Color(242, 242, 242));
        ForgotPassBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/Forgot Pass Text.png"))); // NOI18N
        ForgotPassBTN.setBorder(null);
        ForgotPassBTN.setContentAreaFilled(false);
        ForgotPassBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/Forgot Pass Text Clicked.png"))); // NOI18N
        ForgotPassBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Login/Forgot your Password.png"))); // NOI18N
        ForgotPassBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPassBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ForgotPassBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 180, -1));

        CancelBTN.setBackground(new java.awt.Color(242, 242, 242));
        CancelBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTN.png"))); // NOI18N
        CancelBTN.setBorder(null);
        CancelBTN.setContentAreaFilled(false);
        CancelBTN.setIconTextGap(0);
        CancelBTN.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CancelBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNPressed.png"))); // NOI18N
        CancelBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNRollOver.png"))); // NOI18N
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 3, -1, -1));

        BackgroundUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CovidCareLogin.png"))); // NOI18N
        BackgroundUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundUIMouseClicked(evt);
            }
        });
        getContentPane().add(BackgroundUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 960, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTNActionPerformed
        
        
        String uname = Username.getText();
        String pass = String.valueOf(Password.getPassword());
        String Role;
        
        sql = "SELECT * FROM Users WHERE Uname =? AND Password =?";
        
        try {
            pst = Conn.prepareStatement(sql);
            
            pst.setString(1, uname);
            pst.setString(2, pass);
            
            rs = pst.executeQuery();
            
            if(rs.next())
            {
                    Role = rs.getString("Role");
                    
                    if("admin".equals(Role.toLowerCase().trim()))
                    {
                        DashboardMain_Design Dash = new DashboardMain_Design();
                        Dash.DashUserNameLBL.setText(uname);
                        Dash.UpdataDP(uname);
                        this.setVisible(false);
                        this.dispose();
                        System.out.println("Login in!");
                        Dash.setVisible(true);
                    }
                    else//("user".toLowerCase().trim().equals(Role)) 
                    {
                        
                        DashboardMain_Design Dash = new DashboardMain_Design();
                        Dash.DashUserNameLBL.setText(uname);
                        Dash.UpdataDP(uname);

                        Dash.Register.TabbedPane.removeTabAt(2);
                        Dash.Register.TabbedPane.removeTabAt(1);
                        
                        Dash.Settings.TabbedPane.removeTabAt(1);
                        Report_Design.roleView = false;
                        
                        this.setVisible(false);
                        this.dispose();
                        System.out.println("Login in!");
                        Dash.setVisible(true);
                        
                    }
                    
         
            }
            else{
                    JOptionPane.showMessageDialog(null, "Incorrect Username Or Password", "Login Failed", 2);
                }
            
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_LoginBTNActionPerformed

    private void UsernameTxtBoxIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameTxtBoxIconMouseEntered
        //UsernameTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxFocus.png"));
    }//GEN-LAST:event_UsernameTxtBoxIconMouseEntered

    private void PasswordTxtBoxIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTxtBoxIconMouseEntered
        //PasswordTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxFocus.png"));
    }//GEN-LAST:event_PasswordTxtBoxIconMouseEntered

    private void UsernameTxtBoxIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameTxtBoxIconMouseExited
        //UsernameTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxNormal.png"));
    }//GEN-LAST:event_UsernameTxtBoxIconMouseExited

    private void PasswordTxtBoxIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordTxtBoxIconMouseExited
        //PasswordTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxNormal.png"));
    }//GEN-LAST:event_PasswordTxtBoxIconMouseExited

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        if(Username.getText().equals("Username"))
        {
            Username.setText("");
        }
        UsernameTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxFocus.png"));
    }//GEN-LAST:event_UsernameFocusGained

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost
        if(Username.getText().trim().equals("") || Username.getText().equals("Username"))
        {
           Username.setText("Username");
        }
        UsernameTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxNormal.png"));
    }//GEN-LAST:event_UsernameFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
            
            //VisibleBTN.setIcon(new ImageIcon("src/UI_Images/Login/visibility-off.png"));
            String password = String.valueOf(Password.getPassword());

            if(password.toLowerCase().equals("password"))
            {
                Password.setText("");
                Password.setEchoChar('●');
                VisibleBTN.setIcon(new ImageIcon("src/UI_Images/Login/visibility-off.png"));
            }

            PasswordTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxFocus.png"));
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
            String password = String.valueOf(Password.getPassword());
    
            
            if(password.toLowerCase().equals("password") || password.toLowerCase().equals("") )
            {
                
                Password.setText("Password");
                Password.setEchoChar((char)0);
                VisibleBTN.setIcon(new ImageIcon("src/UI_Images/Login/visibility.png"));
            }


                PasswordTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxNormal.png"));
    }//GEN-LAST:event_PasswordFocusLost

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void UsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseEntered
        //UsernameTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxFocus.png"));
    }//GEN-LAST:event_UsernameMouseEntered

    private void UsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameMouseExited
        //UsernameTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxNormal.png"));
    }//GEN-LAST:event_UsernameMouseExited

    private void PasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseEntered
        //PasswordTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxFocus.png"));
    }//GEN-LAST:event_PasswordMouseEntered

    private void PasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseExited
        //PasswordTxtBoxIcon.setIcon(new ImageIcon("src/UI_Images/Login/TextBoxNormal.png"));
    }//GEN-LAST:event_PasswordMouseExited

    private void SignUpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpBTNActionPerformed
        SignUpStep01 signUp = new SignUpStep01();
        this.dispose();
        signUp.setVisible(true);
    }//GEN-LAST:event_SignUpBTNActionPerformed

    private void VisibleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisibleBTNActionPerformed

    }//GEN-LAST:event_VisibleBTNActionPerformed
    private boolean Sh;

    private void VisibleBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisibleBTNMouseClicked
            if(Sh)
            {
            Sh = false;
            Password.setEchoChar((char)0); //By this line of code. We will actually see the actual characters
            VisibleBTN.setIcon(new ImageIcon("src/UI_Images/Login/visibility.png"));
            }
            else if(!Sh)
            {
            Sh = true;
            Password.setEchoChar('●');
            VisibleBTN.setIcon(new ImageIcon("src/UI_Images/Login/visibility-off.png"));
            }
            //Password.requestFocus();
    }//GEN-LAST:event_VisibleBTNMouseClicked

    private void ForgotPassBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPassBTNActionPerformed
        ForgotPassword open = new ForgotPassword();
        this.setVisible(false);
        this.dispose();
        open.setVisible(true);
    }//GEN-LAST:event_ForgotPassBTNActionPerformed

    private void BackgroundUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundUIMouseClicked
        BackgroundUI.requestFocusInWindow();
    }//GEN-LAST:event_BackgroundUIMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                   try 
                    {
                        UIManager.setLookAndFeel( new FlatLightLaf());
                    } 
                    catch( UnsupportedLookAndFeelException ex ) 
                    {
                        System.err.println( "Failed to initialize LaF" );
                    }

                    new Login().setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundUI;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JButton ForgotPassBTN;
    private javax.swing.JButton LoginBTN;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordTxtBoxIcon;
    private javax.swing.JButton SignUpBTN;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameTxtBoxIcon;
    private javax.swing.JButton VisibleBTN;
    private javax.swing.JCheckBox passCheckBox;
    // End of variables declaration//GEN-END:variables
}
