/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForgotPassword_Design;

import Main.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.synth.SynthLookAndFeel;

/**
 *
 * @author Darkheart
 */
public class ForgotPassword extends javax.swing.JFrame {

    public Connection Conn = null;
    public Statement stmt = null;
    public String sql = "";
    public ResultSet rs = null;
    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        Conn = DBConnection.getconn();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelBTN = new javax.swing.JButton();
        SearchBoxUname = new javax.swing.JTextField();
        SerachBoXUnameLBL = new javax.swing.JLabel();
        SubmitBTN = new javax.swing.JButton();
        BackgroundUI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CancelBTN.setBackground(new java.awt.Color(242, 242, 242));
        CancelBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTN.png"))); // NOI18N
        CancelBTN.setBorder(null);
        CancelBTN.setContentAreaFilled(false);
        CancelBTN.setIconTextGap(0);
        CancelBTN.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CancelBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNPressed.png"))); // NOI18N
        CancelBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNRollOver.png"))); // NOI18N
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 3, -1, -1));

        SearchBoxUname.setBorder(null);
        SearchBoxUname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBoxUnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBoxUnameFocusLost(evt);
            }
        });
        getContentPane().add(SearchBoxUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 300, 30));

        SerachBoXUnameLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/ForgotPassword/SearchUsernameTextBox.png"))); // NOI18N
        getContentPane().add(SerachBoXUnameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 340, 50));

        SubmitBTN.setBackground(new java.awt.Color(242, 242, 242));
        SubmitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/ForgotPassword/SubmitBTNNormal.png"))); // NOI18N
        SubmitBTN.setBorder(null);
        SubmitBTN.setContentAreaFilled(false);
        SubmitBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/ForgotPassword/SumbitBTNSelect.png"))); // NOI18N
        SubmitBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/ForgotPassword/SumbitBTNRoll.png"))); // NOI18N
        SubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 110, 60));

        BackgroundUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/ForgotPassword.png"))); // NOI18N
        getContentPane().add(BackgroundUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelBTNActionPerformed

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
        
        String SearchTxt = SearchBoxUname.getText();
        try 
        {
            
            stmt = Conn.createStatement();
            
            sql = ("select * from Users where ID ='"+SearchTxt+"' or Uname='"+SearchTxt+"'");
            
            rs = stmt.executeQuery(sql);

            while(rs.next())
            {
            String Email = rs.getString("Email");
            String User = rs.getString("Uname");
            ResetPassword reset = new ResetPassword(Email,User);
            
            
            this.setVisible(false);
            this.dispose();
            reset.setVisible(true);
            
            }
        }
                
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
    }//GEN-LAST:event_SubmitBTNActionPerformed

    private void SearchBoxUnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBoxUnameFocusGained
        SerachBoXUnameLBL.setIcon(new ImageIcon("src/UI_Images/ForgotPassword/SearchUsernameTextBoxFocus.png"));
    }//GEN-LAST:event_SearchBoxUnameFocusGained

    private void SearchBoxUnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBoxUnameFocusLost
        SerachBoXUnameLBL.setIcon(new ImageIcon("src/UI_Images/ForgotPassword/SearchUsernameTextBox.png"));
    }//GEN-LAST:event_SearchBoxUnameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
                    try 
                    {
                     UIManager.setLookAndFeel( new SynthLookAndFeel() );
                    } catch( UnsupportedLookAndFeelException ex ) 
                    {
                        System.err.println( "Failed to initialize LaF" );
                    }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
   
            
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundUI;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JTextField SearchBoxUname;
    private javax.swing.JLabel SerachBoXUnameLBL;
    private javax.swing.JButton SubmitBTN;
    // End of variables declaration//GEN-END:variables
}
