/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard_Design;


import Main.DBConnection;
import static Main.DBConnection.closeconn;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.geom.Area;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Darkheart
 */
public class DashboardMain_Design extends javax.swing.JFrame {

    
    public Analytics_Design  Analytics = new Analytics_Design();
    public Report_Design Report = new Report_Design();
    public Register_Design Register = new Register_Design();
    public SendAlert_Design SendAlert = new SendAlert_Design();
    public IssueID_Design IssueID = new IssueID_Design();
    public Settings_Design Settings = new Settings_Design();
    public Home_Design Home = new Home_Design();
    public static Connection Conn = null;
    public Statement stmt = null;
    public PreparedStatement pst = null;
    public String sql = "";
    public ResultSet rs = null;
    public String path;
    private ImageIcon format = null;
    
    
    
    /**
     * Creates new form DashboardMain_Design
     */
    public DashboardMain_Design() {

        
        initComponents();
        Conn = DBConnection.getconn();
        
        LocalDate today = LocalDate.now( ZoneId.of( "Asia/Colombo" ));
        TodayDate.setText(today.toString());
        BackgroundUI.requestFocusInWindow();
        
        PanelsSwitch(Home);
        Home.VA.setText(String.valueOf(Analytics.AvailbleTotalDose()));
        
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CancelBTN = new javax.swing.JButton();
        HomeBTN = new javax.swing.JButton();
        AnalyticsBTN = new javax.swing.JButton();
        ReportBTN = new javax.swing.JButton();
        RegisterBTN = new javax.swing.JButton();
        SendAlertBTN = new javax.swing.JButton();
        IssueIdBTN = new javax.swing.JButton();
        SettingsBTN = new javax.swing.JButton();
        DragPanel = new javax.swing.JPanel();
        DashTabName = new javax.swing.JLabel();
        DashTabNameIcon = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        DashSearchWigdet = new javax.swing.JLabel();
        DashDP1 = new javax.swing.JLabel();
        DashUserNameLBL = new javax.swing.JLabel();
        TodayDate = new javax.swing.JLabel();
        DashDateWidget = new javax.swing.JLabel();
        LayeredPane = new javax.swing.JLayeredPane();
        BackgroundUI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1220, 650));
        setMinimumSize(new java.awt.Dimension(1220, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1220, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CancelBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTN.png"))); // NOI18N
        CancelBTN.setBorder(null);
        CancelBTN.setBorderPainted(false);
        CancelBTN.setContentAreaFilled(false);
        CancelBTN.setIconTextGap(0);
        CancelBTN.setMargin(new java.awt.Insets(0, 0, 0, 0));
        CancelBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNPressed.png"))); // NOI18N
        CancelBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CancelBTN/CancelBTNRollOver.png"))); // NOI18N
        CancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        HomeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuNormalBTN/HomeBTN.png"))); // NOI18N
        HomeBTN.setBorder(null);
        HomeBTN.setContentAreaFilled(false);
        HomeBTN.setDisabledSelectedIcon(null);
        HomeBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuSelected/HomeBTN.png"))); // NOI18N
        HomeBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuRollover/HomeBTN.png"))); // NOI18N
        HomeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(HomeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 266, 56));

        AnalyticsBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuNormalBTN/AnalyticsBTN.png"))); // NOI18N
        AnalyticsBTN.setBorder(null);
        AnalyticsBTN.setContentAreaFilled(false);
        AnalyticsBTN.setPreferredSize(new java.awt.Dimension(266, 56));
        AnalyticsBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuSelected/AnalyticsBTN.png"))); // NOI18N
        AnalyticsBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuRollover/AnalyticsBTN.png"))); // NOI18N
        AnalyticsBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnalyticsBTNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AnalyticsBTNMousePressed(evt);
            }
        });
        AnalyticsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalyticsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(AnalyticsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 266, 56));

        ReportBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuNormalBTN/ReportBTN.png"))); // NOI18N
        ReportBTN.setBorder(null);
        ReportBTN.setContentAreaFilled(false);
        ReportBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuSelected/ReportBTN.png"))); // NOI18N
        ReportBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuRollover/ReportBTN.png"))); // NOI18N
        ReportBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ReportBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 266, 56));

        RegisterBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuNormalBTN/RegisterBTN.png"))); // NOI18N
        RegisterBTN.setBorder(null);
        RegisterBTN.setContentAreaFilled(false);
        RegisterBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuSelected/RegisterBTN.png"))); // NOI18N
        RegisterBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuRollover/RegisterBTN.png"))); // NOI18N
        RegisterBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBTNActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 266, 56));

        SendAlertBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuNormalBTN/SendAlertBTN.png"))); // NOI18N
        SendAlertBTN.setBorder(null);
        SendAlertBTN.setContentAreaFilled(false);
        SendAlertBTN.setMaximumSize(new java.awt.Dimension(266, 56));
        SendAlertBTN.setMinimumSize(new java.awt.Dimension(266, 56));
        SendAlertBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuSelected/SendAlertBTN.png"))); // NOI18N
        SendAlertBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuRollover/SendAlertBTN.png"))); // NOI18N
        SendAlertBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendAlertBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SendAlertBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 266, 56));

        IssueIdBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuNormalBTN/IssueIdBTN.png"))); // NOI18N
        IssueIdBTN.setBorder(null);
        IssueIdBTN.setContentAreaFilled(false);
        IssueIdBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuSelected/IssueIdBTN.png"))); // NOI18N
        IssueIdBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuRollover/IssueIdBTN.png"))); // NOI18N
        IssueIdBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueIdBTNActionPerformed(evt);
            }
        });
        getContentPane().add(IssueIdBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 266, 56));

        SettingsBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuNormalBTN/SettingsBTN.png"))); // NOI18N
        SettingsBTN.setBorder(null);
        SettingsBTN.setContentAreaFilled(false);
        SettingsBTN.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuSelected/SettingsBTN.png"))); // NOI18N
        SettingsBTN.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/MenuRollover/SettingsBTN.png"))); // NOI18N
        SettingsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SettingsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 266, 56));

        DragPanel.setOpaque(false);
        DragPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                DragPanelMouseDragged(evt);
            }
        });
        DragPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DragPanelMousePressed(evt);
            }
        });
        DragPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(DragPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 30));

        DashTabName.setBackground(new java.awt.Color(255, 255, 255));
        DashTabName.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        DashTabName.setForeground(new java.awt.Color(23, 23, 37));
        DashTabName.setText("Home");
        getContentPane().add(DashTabName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, 60));

        DashTabNameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/DashTabLBL.png"))); // NOI18N
        DashTabNameIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashTabNameIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashTabNameIconMouseExited(evt);
            }
        });
        getContentPane().add(DashTabNameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 160, 50));

        Search.setText("Search...");
        Search.setBorder(null);
        Search.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Search.setOpaque(true);
        Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFocusLost(evt);
            }
        });
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SearchMouseExited(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 27, 140, 20));

        DashSearchWigdet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/SearchNormal.png"))); // NOI18N
        DashSearchWigdet.setDoubleBuffered(true);
        DashSearchWigdet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashSearchWigdetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashSearchWigdetMouseExited(evt);
            }
        });
        getContentPane().add(DashSearchWigdet, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 16, 250, 50));

        DashDP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user_50px.png"))); // NOI18N
        DashDP1.setDoubleBuffered(true);
        DashDP1.setIconTextGap(0);
        getContentPane().add(DashDP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 50, 50));

        DashUserNameLBL.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        DashUserNameLBL.setText("Username");
        DashUserNameLBL.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                DashUserNameLBLComponentShown(evt);
            }
        });
        getContentPane().add(DashUserNameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 110, 30));

        TodayDate.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        TodayDate.setText("2021-09-02");
        getContentPane().add(TodayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 140, 60));

        DashDateWidget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/DateWidgetNormal.png"))); // NOI18N
        DashDateWidget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashDateWidgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashDateWidgetMouseExited(evt);
            }
        });
        getContentPane().add(DashDateWidget, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 240, 50));

        LayeredPane.setBackground(new java.awt.Color(255, 255, 255));
        LayeredPane.setDoubleBuffered(true);
        LayeredPane.setMaximumSize(new java.awt.Dimension(950, 510));
        LayeredPane.setMinimumSize(new java.awt.Dimension(950, 510));
        LayeredPane.setLayout(new java.awt.CardLayout());
        getContentPane().add(LayeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 140, 950, 510));

        BackgroundUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/Dashboard.png"))); // NOI18N
        BackgroundUI.setAutoscrolls(true);
        BackgroundUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundUIMouseClicked(evt);
            }
        });
        getContentPane().add(BackgroundUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBTNActionPerformed
        
        if (JOptionPane.showConfirmDialog( this,"Confirm if you want to Exit","Covid Care",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
           try {
            closeconn();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardMain_Design.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
        }
        

        
    }//GEN-LAST:event_CancelBTNActionPerformed
    public int xx,xy;
    private void DragPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMouseDragged
                int x = evt.getXOnScreen();
                int y = evt.getYOnScreen();
                this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_DragPanelMouseDragged

    private void DragPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DragPanelMousePressed
               xx = evt.getX();
               xy = evt.getY();
    }//GEN-LAST:event_DragPanelMousePressed

    private void HomeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBTNActionPerformed
        MenuBTNReset();
        HomeBTN.setIcon(new ImageIcon("src/UI_Images/MenuSelected/HomeBTN.png"));
        HomeBTN.getModel().setRollover(false);
        DashTabName.setText("Home");
        PanelsSwitch(Home);
        Home.WelcomeILL.setVisible(false);
        Home.WelcomeText.setVisible(false);
        Home.HomeBGSlideShow.setVisible(true);
        Home.UpdateLBL();
        Home.VA.setText(String.valueOf(Analytics.AvailbleTotalDose()));
    }//GEN-LAST:event_HomeBTNActionPerformed

    @Override
    public boolean isAutoRequestFocus() {
        return super.isAutoRequestFocus(); //To change body of generated methods, choose Tools | Templates.
    }
    private boolean atrue = false;
    private void AnalyticsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalyticsBTNActionPerformed
        MenuBTNReset();
        AnalyticsBTN.setIcon(new ImageIcon("src/UI_Images/MenuSelected/AnalyticsBTN.png"));
        AnalyticsBTN.getModel().setRollover(false);
        DashTabName.setText("Analytics");
        
        //Analytics_Design  Analytics = new Analytics_Design();
        
        PanelsSwitch(new Analytics_Design());
        
        //Analytics.updateCharts();

    }//GEN-LAST:event_AnalyticsBTNActionPerformed

    private void ReportBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportBTNActionPerformed
        MenuBTNReset();
        ReportBTN.setIcon(new ImageIcon("src/UI_Images/MenuSelected/ReportBTN.png"));
        ReportBTN.getModel().setRollover(false);
        DashTabName.setText("Report");
        
        Report.ViewerPanel.setVisible(false);
        Report.ReportShowPanel.setVisible(true);
        Report.ReportPanel.repaint();
        Report.ReportPanel.revalidate();
        
        PanelsSwitch(Report);
        
    }//GEN-LAST:event_ReportBTNActionPerformed

    private void RegisterBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBTNActionPerformed
        MenuBTNReset();
        RegisterBTN.setIcon(new ImageIcon("src/UI_Images/MenuSelected/RegisterBTN.png"));
        RegisterBTN.getModel().setRollover(false);
        DashTabName.setText("Register");

        PanelsSwitch(Register);
    }//GEN-LAST:event_RegisterBTNActionPerformed

    private void SendAlertBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendAlertBTNActionPerformed
        MenuBTNReset();
        SendAlertBTN.setIcon(new ImageIcon("src/UI_Images/MenuSelected/SendAlertBTN.png"));
        SendAlertBTN.getModel().setRollover(false);
        DashTabName.setText("Send Alert");
        PanelsSwitch(SendAlert);
        
    }//GEN-LAST:event_SendAlertBTNActionPerformed

    private void IssueIdBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueIdBTNActionPerformed
        MenuBTNReset();
        IssueIdBTN.setIcon(new ImageIcon("src/UI_Images/MenuSelected/IssueIdBTN.png"));
        IssueIdBTN.getModel().setRollover(false);
        DashTabName.setText("Issue ID");
        PanelsSwitch(IssueID);
        
    }//GEN-LAST:event_IssueIdBTNActionPerformed

    private void SettingsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsBTNActionPerformed
        MenuBTNReset();
        SettingsBTN.setIcon(new ImageIcon("src/UI_Images/MenuSelected/SettingsBTN.png"));
        SettingsBTN.getModel().setRollover(false);
        DashTabName.setText("Settings");
        PanelsSwitch(Settings);
        Settings.updateTable();
        
    }//GEN-LAST:event_SettingsBTNActionPerformed
    private Boolean Sfocus = false;
    private void SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusGained
        Sfocus = true;
        DashSearchWigdet.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/SearchFocus.png"));
        if(Search.getText().equals("Search..."))
        {
            Search.setText("");
        }
    }//GEN-LAST:event_SearchFocusGained

    private void SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusLost
        Sfocus = false;
        DashSearchWigdet.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/SearchNormal.png"));
        if(Search.getText().trim().equals("") || Search.getText().equals("Search..."))
        {
        Search.setText("Search...");
        }
    }//GEN-LAST:event_SearchFocusLost

    private void BackgroundUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundUIMouseClicked
        BackgroundUI.requestFocusInWindow();
    }//GEN-LAST:event_BackgroundUIMouseClicked

    private void DashTabNameIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashTabNameIconMouseEntered
        DashTabNameIcon.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/DashTabLBL.png"));
    }//GEN-LAST:event_DashTabNameIconMouseEntered

    private void DashTabNameIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashTabNameIconMouseExited
        DashTabNameIcon.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/DashTabLBL.png"));
    }//GEN-LAST:event_DashTabNameIconMouseExited

    private void DashSearchWigdetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashSearchWigdetMouseEntered
        if(!Sfocus)
        {
        DashSearchWigdet.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/SearchRollover.png"));
        }
    }//GEN-LAST:event_DashSearchWigdetMouseEntered

    private void DashSearchWigdetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashSearchWigdetMouseExited
        if(!Sfocus)
        {
        DashSearchWigdet.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/SearchNormal.png"));
        }
    }//GEN-LAST:event_DashSearchWigdetMouseExited

    private void DashDateWidgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashDateWidgetMouseEntered
        DashDateWidget.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/DateRollover.png"));
    }//GEN-LAST:event_DashDateWidgetMouseEntered

    private void DashDateWidgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashDateWidgetMouseExited
        DashDateWidget.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/DateWidgetNormal.png"));
    }//GEN-LAST:event_DashDateWidgetMouseExited

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        if(!Sfocus)
        {
        DashSearchWigdet.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/SearchRollover.png"));
        }
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseExited
        if(!Sfocus)
        {
        DashSearchWigdet.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/SearchNormal.png"));
        }
    }//GEN-LAST:event_SearchMouseExited

    private void AnalyticsBTNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalyticsBTNMousePressed

    }//GEN-LAST:event_AnalyticsBTNMousePressed

    private void AnalyticsBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnalyticsBTNMouseClicked

    }//GEN-LAST:event_AnalyticsBTNMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (JOptionPane.showConfirmDialog( this,"Confirm if you want to Exit","Covid Care",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
           try {
            closeconn();
            IssueID.comPort.closePort();
        } catch (SQLException ex) {
            Logger.getLogger(DashboardMain_Design.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
        System.out.println("window closing");
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void DashUserNameLBLComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_DashUserNameLBLComponentShown
        
    }//GEN-LAST:event_DashUserNameLBLComponentShown

    public void UpdataDP(String Uname)
    {
        try{    
                sql = "select * from Users where Uname = ?";
                pst = Conn.prepareStatement(sql);
                pst.setString(1, Uname);
                rs = pst.executeQuery();
                
                if(rs.next()){
                    
                    byte[] img = rs.getBytes("DP");
                    System.out.println(DashUserNameLBL.getText());                    
                    InputStream is = new ByteArrayInputStream(img);
                    BufferedImage image2 = ImageIO.read(is);

                    Area clip = new Area( new Rectangle(0, 0, image2.getWidth(), image2.getHeight()) );
                    Area oval = new Area( new Ellipse2D.Double(0, 0, image2.getWidth() - 1, image2.getHeight() - 1) );
                    clip.subtract( oval );
                    Graphics g2d = image2.createGraphics();
                    g2d.setClip( clip );
                    g2d.setColor( Color.WHITE );
                    g2d.fillRect(0, 0, image2.getWidth(), image2.getHeight());
                    
                    
                    Image img2= image2.getScaledInstance(DashDP1.getWidth(),DashDP1.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon image3=new ImageIcon(img2);
                    DashDP1.setIcon(image3);
                    System.out.println("DP image Loaded!");
                }
                
                else{
                    System.out.println("No DP image Loaded!");
                }
                }catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex.toString());
                ex.printStackTrace();
            } catch (IOException ex) {
            Logger.getLogger(DashboardMain_Design.class.getName()).log(Level.SEVERE, null, ex);
        }


    }
    
    public void MenuBTNReset()
    {
        HomeBTN.setIcon(new ImageIcon("src/UI_Images/MenuNormalBTN/HomeBTN.png"));
        AnalyticsBTN.setIcon(new ImageIcon("src/UI_Images/MenuNormalBTN/AnalyticsBTN.png"));
        ReportBTN.setIcon(new ImageIcon("src/UI_Images/MenuNormalBTN/ReportBTN.png"));
        RegisterBTN.setIcon(new ImageIcon("src/UI_Images/MenuNormalBTN/RegisterBTN.png"));
        SendAlertBTN.setIcon(new ImageIcon("src/UI_Images/MenuNormalBTN/SendAlertBTN.png"));
        IssueIdBTN.setIcon(new ImageIcon("src/UI_Images/MenuNormalBTN/IssueIdBTN.png"));
        SettingsBTN.setIcon(new ImageIcon("src/UI_Images/MenuNormalBTN/SettingsBTN.png"));
    }
    
    public void PanelsSwitch(JPanel panel)
    {
        
        LayeredPane.removeAll();
        LayeredPane.add(panel);
        LayeredPane.repaint();
        LayeredPane.revalidate();
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
              
        /* Create and display the form */
    
                    
                    try 
                    {
                        UIManager.setLookAndFeel( new FlatLightLaf());
                        UIManager.getLookAndFeelDefaults().put("Panel.background", Color.WHITE);
                        
                        UIManager.getLookAndFeelDefaults().put("ScrollPane.border", "com.formdev.flatlaf.ui.FlatEmptyBorder@6b01ab73");
                        UIManager.getLookAndFeelDefaults().put("Table.scrollPaneBorder", "com.formdev.flatlaf.ui.FlatEmptyBorder@6b01ab73");
                        //UIManager.put("TabbedPane.contentOpaque", true);


                    } catch( UnsupportedLookAndFeelException ex ) 
                    {
                        System.err.println( "Failed to initialize LaF" );
                    }
                    
                    DashboardMain_Design frame = new DashboardMain_Design();
                    frame.setVisible(true);
                    
                    /*
                    ComponentResizerUtil cr = new ComponentResizerUtil();
                    frame.getRootPane().setBorder(new LineBorder(Color.gray));
                    cr.setSnapSize(new Dimension(5, 5));
                    cr.setDragInsets(new Insets(5, 5, 5, 5));
                
                    //always register frame to resize
                    cr.registerComponent(frame);
               
                    //DashboardMain_Design frame = new DashboardMain_Design();
                    //frame.setVisible(true);
                    */

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalyticsBTN;
    private javax.swing.JLabel BackgroundUI;
    private javax.swing.JButton CancelBTN;
    private javax.swing.JLabel DashDP1;
    private javax.swing.JLabel DashDateWidget;
    private javax.swing.JLabel DashSearchWigdet;
    private javax.swing.JLabel DashTabName;
    private javax.swing.JLabel DashTabNameIcon;
    public javax.swing.JLabel DashUserNameLBL;
    private javax.swing.JPanel DragPanel;
    private javax.swing.JButton HomeBTN;
    private javax.swing.JButton IssueIdBTN;
    public javax.swing.JLayeredPane LayeredPane;
    private javax.swing.JButton RegisterBTN;
    private javax.swing.JButton ReportBTN;
    private javax.swing.JTextField Search;
    private javax.swing.JButton SendAlertBTN;
    private javax.swing.JButton SettingsBTN;
    private javax.swing.JLabel TodayDate;
    // End of variables declaration//GEN-END:variables
}
