/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Dashboard_Design;

import Main.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author Darkheart
 */
public class Home_Design extends javax.swing.JPanel {

    public static Connection Conn = null;
    public Statement stmt = null;
    public PreparedStatement pst = null;
    public String sql = "";
    public ResultSet rs = null;
    
    /**
     * Creates new form HomeWelcomePanel
     */
    public Home_Design() {
        initComponents();
        Conn = DBConnection.getconn();
        UpdateLBL();
        HomeBGSlideShow.setVisible(false);
        new java.util.Timer().schedule( 
        new java.util.TimerTask() {
            @Override
            public void run() {
                
                        WelcomeILL.setVisible(false);
                        WelcomeText.setVisible(false);
                        HomeBGSlideShow.setVisible(true);
            }
        }, 
        7000 
        );
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HomePanel = new javax.swing.JPanel();
        PV = new javax.swing.JLabel();
        VA = new javax.swing.JLabel();
        PFV = new javax.swing.JLabel();
        FV = new javax.swing.JLabel();
        VAICON = new javax.swing.JLabel();
        FVICON = new javax.swing.JLabel();
        PFVICON = new javax.swing.JLabel();
        PVICON = new javax.swing.JLabel();
        WidgetLabel1 = new javax.swing.JLabel();
        WidgetLabel2 = new javax.swing.JLabel();
        WidgetLabel3 = new javax.swing.JLabel();
        WidgetLabel4 = new javax.swing.JLabel();
        HomeBGSlideShow = new javax.swing.JLabel();
        WelcomeILL = new javax.swing.JLabel();
        WelcomeText = new javax.swing.JLabel();
        DashMainWidgetLabel1 = new javax.swing.JLabel();

        setOpaque(false);

        HomePanel.setMaximumSize(new java.awt.Dimension(950, 510));
        HomePanel.setMinimumSize(new java.awt.Dimension(950, 510));
        HomePanel.setOpaque(false);
        HomePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PV.setBackground(new java.awt.Color(255, 255, 255));
        PV.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        PV.setForeground(new java.awt.Color(97, 123, 253));
        PV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PV.setText("500100");
        PV.setDoubleBuffered(true);
        HomePanel.add(PV, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 60, 80, 20));

        VA.setBackground(new java.awt.Color(255, 255, 255));
        VA.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        VA.setForeground(new java.awt.Color(97, 123, 253));
        VA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VA.setText("1000100");
        VA.setDoubleBuffered(true);
        HomePanel.add(VA, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 60, 80, 20));

        PFV.setBackground(new java.awt.Color(255, 255, 255));
        PFV.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        PFV.setForeground(new java.awt.Color(97, 123, 253));
        PFV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PFV.setText("51%");
        PFV.setDoubleBuffered(true);
        HomePanel.add(PFV, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 80, 20));

        FV.setBackground(new java.awt.Color(255, 255, 255));
        FV.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        FV.setForeground(new java.awt.Color(97, 123, 253));
        FV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FV.setText("100100");
        FV.setDoubleBuffered(true);
        HomePanel.add(FV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, 20));

        VAICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/VaccinesAvailableWidget.png"))); // NOI18N
        VAICON.setDoubleBuffered(true);
        HomePanel.add(VAICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 120, 100));

        FVICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/FullyVacinatedWidget.png"))); // NOI18N
        FVICON.setDoubleBuffered(true);
        HomePanel.add(FVICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 18, 110, 100));

        PFVICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/PopulationFullyVaccinatedWidget.png"))); // NOI18N
        PFVICON.setDoubleBuffered(true);
        HomePanel.add(PFVICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 12, 170, 100));

        PVICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/PartiallyVaccinatedWidget.png"))); // NOI18N
        PVICON.setDoubleBuffered(true);
        HomePanel.add(PVICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 18, 130, 100));

        WidgetLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/DashWidget.png"))); // NOI18N
        WidgetLabel1.setDoubleBuffered(true);
        WidgetLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WidgetLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WidgetLabel1MouseExited(evt);
            }
        });
        HomePanel.add(WidgetLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 14, 210, 110));

        WidgetLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/DashWidget.png"))); // NOI18N
        WidgetLabel2.setDoubleBuffered(true);
        WidgetLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WidgetLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WidgetLabel2MouseExited(evt);
            }
        });
        HomePanel.add(WidgetLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 14, 210, 110));

        WidgetLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/DashWidget.png"))); // NOI18N
        WidgetLabel3.setDoubleBuffered(true);
        WidgetLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WidgetLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WidgetLabel3MouseExited(evt);
            }
        });
        HomePanel.add(WidgetLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 14, 210, 110));

        WidgetLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/DashWidget.png"))); // NOI18N
        WidgetLabel4.setDoubleBuffered(true);
        WidgetLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WidgetLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WidgetLabel4MouseExited(evt);
            }
        });
        HomePanel.add(WidgetLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 14, 210, 110));

        HomeBGSlideShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/CovidCareHomeGif.gif"))); // NOI18N
        HomePanel.add(HomeBGSlideShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 840, 330));

        WelcomeILL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/WelcomeILL.png"))); // NOI18N
        HomePanel.add(WelcomeILL, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 146, 470, 330));

        WelcomeText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/WelcomeToCovidCare.png"))); // NOI18N
        HomePanel.add(WelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 290, 270));

        DashMainWidgetLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Images/DashNormalWidget/DashHomeMainWidget.png"))); // NOI18N
        DashMainWidgetLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashMainWidgetLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashMainWidgetLabel1MouseExited(evt);
            }
        });
        HomePanel.add(DashMainWidgetLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, 930, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void UpdateLBL()
    {
        try 
        {
            
            stmt = Conn.createStatement();
            
            sql = ("SELECT COUNT(*) FROM dosestatus WHERE FirstDoseStatus = 'Taken' AND SecondDoseStatus = 'Taken'");
            rs = stmt.executeQuery(sql);
            
 
            while(rs.next())
            {

            FV.setText(rs.getString(1));
            
            }
        }
                
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        try 
        {
            
            stmt = Conn.createStatement();
            
            sql = ("SELECT COUNT(*) FROM dosestatus WHERE FirstDoseStatus = 'Taken' AND SecondDoseStatus = 'Not Taken'");
            rs = stmt.executeQuery(sql);
            
 
            while(rs.next())
            {

            PV.setText(rs.getString(1));
            
            }
        }
                
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        /*stmt = Conn.createStatement();
        
        sql = ("SELECT SUM(Quantity) FROM vaccines");
        rs = stmt.executeQuery(sql);
        
        
        while(rs.next())
        {*/
        
        
        
        //}
        
        try 
        {
            
            stmt = Conn.createStatement();

            
            sql = ("SELECT 100. * count(*) / sum(21522704) over () FROM dosestatus WHERE FirstDoseStatus = 'Taken' AND SecondDoseStatus = 'Taken'");
            rs = stmt.executeQuery(sql);
            
 
            while(rs.next())
            {
                
            Double Populatiton = 51.00;
            String PopPlus = String.format("%.0f",Populatiton+Double.valueOf(rs.getString(1)));

            PFV.setText(PopPlus+"%");
            
            }
        }
                
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }
    
    private void WidgetLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel1MouseEntered
        WidgetLabel1.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel1MouseEntered

    private void WidgetLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel1MouseExited
        WidgetLabel1.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel1MouseExited

    private void WidgetLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel2MouseEntered
        WidgetLabel2.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel2MouseEntered

    private void WidgetLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel2MouseExited
        WidgetLabel2.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel2MouseExited

    private void WidgetLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel3MouseEntered
        WidgetLabel3.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel3MouseEntered

    private void WidgetLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel3MouseExited
        WidgetLabel3.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel3MouseExited

    private void WidgetLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel4MouseEntered
        WidgetLabel4.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel4MouseEntered

    private void WidgetLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WidgetLabel4MouseExited
        WidgetLabel4.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/DashWidget.png"));
    }//GEN-LAST:event_WidgetLabel4MouseExited

    private void DashMainWidgetLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashMainWidgetLabel1MouseEntered
        DashMainWidgetLabel1.setIcon(new ImageIcon("src/UI_Images/DashRolloverWidget/DashHomeWigdet.png"));
    }//GEN-LAST:event_DashMainWidgetLabel1MouseEntered

    private void DashMainWidgetLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashMainWidgetLabel1MouseExited
        DashMainWidgetLabel1.setIcon(new ImageIcon("src/UI_Images/DashNormalWidget/DashHomeMainWidget.png"));
    }//GEN-LAST:event_DashMainWidgetLabel1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DashMainWidgetLabel1;
    private javax.swing.JLabel FV;
    private javax.swing.JLabel FVICON;
    public javax.swing.JLabel HomeBGSlideShow;
    public javax.swing.JPanel HomePanel;
    private javax.swing.JLabel PFV;
    private javax.swing.JLabel PFVICON;
    private javax.swing.JLabel PV;
    private javax.swing.JLabel PVICON;
    public javax.swing.JLabel VA;
    private javax.swing.JLabel VAICON;
    public javax.swing.JLabel WelcomeILL;
    public javax.swing.JLabel WelcomeText;
    public javax.swing.JLabel WidgetLabel1;
    private javax.swing.JLabel WidgetLabel2;
    private javax.swing.JLabel WidgetLabel3;
    private javax.swing.JLabel WidgetLabel4;
    // End of variables declaration//GEN-END:variables
}
